### PR TITLE
fix

### PR DESCRIPTION
**Pull request by git-bruh**

### CODE REVIEW

**Review by icebarf — CHANGES_REQUESTED** [review]
Please remove the first two comments as the makefile isn't by me anymore. I can't take credit for that. The makefile looks superclean and miles better than I could have done. LGTM

**Review by icebarf — APPROVED** [review]
Thanks for the cleanup, the bins were just for tracking

**Comment by git-bruh** [comment]
Done. BTW this also removes building in a separate build directory cuz it leads to a lot of issues and is hacky, better use meson or something for that.

**Comment by icebarf** [comment]
Thank you for your contribution. Really appreciate your help!

**Pull request merged**
